services:
  backend:
    build:
      context: ./backend
    container_name: afc-backend
    env_file:
      - backend.env
    ports:
      - "5000:5000"

  app:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    container_name: afc-app
    env_file:
      - web.env
    ports:
      - "8080:10000"
    depends_on:
      - backend

    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro